# Generated by Django 5.2.3 on 2025-07-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_activeticket_delete_archivedticket_archivedticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveTicket',
        ),
        migrations.DeleteModel(
            name='ArchivedTicket',
        ),
    ]
